- name: "AWS | ECS | Check ECS cluster name has been defined"
  fail: msg="You must specify the name of the ECS cluster, e.g. my-cluster"
  when: ecs_cluster_name is undefined
  vars:
    ecs_cluster_name: "DdackCluster"

- name: "AWS | ECS | Check EC2 SSH key has been defined"
  fail: msg="You must specify the name of the SSH key you want to assign to the EC2 instances, e.g. my-ssh-key"
  when: ecs_ssh_key_name is undefined
  vars:
    ecs_ssh_key_name: "Ddackkey"

- name: "AWS | ECS | Check EC2 security groups have been defined"
  fail: msg="You must specify a list of existing EC2 security groups IDs to apply to the auto-scaling EC2 instances"
  when: ecs_security_groups is undefined and ecs_state == "present"
  vars:
    ecs_security_groups: "DdackSG1"

- name: "AWS | ECS | Check VPC subnets have been defined"
  fail: msg="You must specify a list of existing VPC subnets for which to provision the EC2 nodes into"
  when: ecs_vpc_subnets is undefined and ecs_state == "present"
  vars:
    ecs_vpc_subnets:
      - "{{ subnet_result.subnet.id }}"
      - "{{ subnet_result2.subnet.id }}"

